logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
server:
  error:
    include-binding-errors: always
    whitelabel:
      enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://mano-auth:8080/auth/realms/mano-realm