logging:
  level:
    root: INFO

management:
  elastic:
    metrics:
      export:
        host: http://mano-es:9200
        index: mano-metrics-helm3
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0

server:
  error:
    include-binding-errors: always
    whitelabel:
      enabled: false

spring:
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://mano-auth:8080/auth/realms/mano-realm