apiVersion: v1
clusters:
- cluster:
    certificate-authority: ca.pem
    server: {{SERVER_API}}
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate: client-crt.pem
    client-key: client-key.pem
